spring:
  datasource:
    url: 'jdbc:mysql://${DB_HOST:${DB_DATABASE_HOST}}:3306/${DB_DATABASE}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
    platform: mysql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
  mvc:
    log-request-details: true

REACT_CLIENT: '${REACT_CLIENT}'

logging:
  level:
    org:
      springframework:
        web: DEBUG
jwt:
  public-key: 'classpath:certs/public-key.pem'
  private-key: 'classpath:certs/private-key.pem'

client:
  url: ${REACT_CLIENT_URL} 