spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_DATABASE_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    platform: mysql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  mvc:
    log-request-details: true

logging:
  level:
    web: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
jwt:
  public-key: classpath:certs/public-key.pem
  private-key: classpath:certs/private-key.pem

server:
  port : 5000

client:
  url: ${REACT_CLIENT_URL} 
