spring:
  datasource:
    url: 'jdbc:mysql://${MYSQL_HOST:${MYSQL_DATABASE_HOST}}:3306/${MYSQL_DATABASE}'
    username: '${MYSQL_USERNAME}'
    password: '${MYSQL_PASSWORD}'
    platform: mysql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    log-request-details: true

JWT_SIGNATURE: '${JWT_SIGNATURE}'
REACT_CLIENT: '${REACT_CLIENT}'

logging:
  level:
    org:
      springframework:
        web: DEBUG
jwt:
  public-key: 'classpath:certs/public-key.pem'
  private-key: 'classpath:certs/private-key.pem'
