spring:
  datasource:
    url: jdbc:hsqldb:mem:motivedb
    username: username
    password: password
    initialization-mode: always
  driverClassName: org.hsqldb.jdbcDriver  
  jpa:
    database: HSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        ddl-auto: create-drop
  mvc:
    log-request-details: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
jwt:
  public-key: 'classpath:certs/public-key.pem'
  private-key: 'classpath:certs/private-key.pem'
     
client:
  url: localhost