name: Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Openssl RSA Files
      shell: bash
      run: ./.github/workflows/dependencies/openssl.sh
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
    - name: Build with Gradle
      env:
        SPRING_PROFILES_ACTIVE: test
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build --debug
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ./build/libs/motive-rest-0.0.1-SNAPSHOT.jar
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact
      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: false
          application_name: motive-rest-api-dev
          environment_name: Motive-rest-api-dev-env
          version_label: ${{github.SHA}}
          region: us-east-1
          deployment_package: motive-rest-0.0.1-SNAPSHOT.jar    