# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MARIADB_ROOT_PASSWORD: 'root'
          MARIADB_DB: 'motivedb'
          MARIADB_USER: 'motiveuser'
          MARIADB_PASSWORD: 'motivepassword'
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Create Openssl RSA Files
      shell: bash
      run: ./.github/workflows/create-openssl-keys.sh
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      env:
        JWT_SIGNATURE: '48b4d3e5-3220-4068-bb28-9d4d5a1fbeb0'
        DB_USERNAME: 'motiveuser'
        DB_PASSWORD: 'motivepassword'
        DB_DATABASE_HOST: 'localhost'
        DB_DATABASE: 'motivedb'
        REACT_CLIENT_URL: '192.168.1.149:19000'
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build --debug

# export JWT_SIGNATURE=48b4d3e5-3220-4068-bb28-9d4d5a1fbeb0 && export DB_USERNAME=motiveuser && export DB_PASSWORD=motivepassword && export DB_DATABASE_HOST=localhost && export DB_DATABASE=motivedb && export REACT_CLIENT_URL='192.168.1.149:19000'